"""CPU reference and logical EP simulation pieces for nano-moe-ep."""

from nano_moe_ep.distributed_ep import (
    CountExchange,
    DistributedEPConfig,
    DistributedEPTrace,
    DistributedPayloadPlan,
    apply_partial_combine,
    apply_sharded_combine,
    apply_sharded_topk_combine,
    build_distributed_payload_plan,
    build_distributed_topk_payload_plan,
    run_distributed_ep_moe,
    run_distributed_topk_ep_moe,
    source_token_indices,
)
from nano_moe_ep.dispatch_combine import LogicalEPTrace, run_logical_ep_moe
from nano_moe_ep.reference import ReferenceMoEFFN, TopKReferenceMoEFFN
from nano_moe_ep.routing import (
    build_capacity_mask,
    compute_expert_capacity,
    expert_load,
    route_topk_explicit,
    route_topk_round_robin,
)
from nano_moe_ep.types import (
    CombinePlan,
    DispatchPlan,
    EPContext,
    ExecutionMode,
    ExpertPlacement,
    ReferenceTrace,
    RouterOutput,
    TokenAssignment,
    TokenLayout,
    TopKReferenceTrace,
    TopKRouterOutput,
)

__all__ = [
    "CombinePlan",
    "CountExchange",
    "DispatchPlan",
    "DistributedEPConfig",
    "DistributedEPTrace",
    "DistributedPayloadPlan",
    "EPContext",
    "ExecutionMode",
    "ExpertPlacement",
    "LogicalEPTrace",
    "ReferenceMoEFFN",
    "ReferenceTrace",
    "RouterOutput",
    "TokenAssignment",
    "TokenLayout",
    "TopKReferenceMoEFFN",
    "TopKReferenceTrace",
    "TopKRouterOutput",
    "apply_partial_combine",
    "apply_sharded_combine",
    "apply_sharded_topk_combine",
    "build_capacity_mask",
    "build_distributed_payload_plan",
    "build_distributed_topk_payload_plan",
    "compute_expert_capacity",
    "expert_load",
    "route_topk_explicit",
    "route_topk_round_robin",
    "run_distributed_ep_moe",
    "run_distributed_topk_ep_moe",
    "run_logical_ep_moe",
    "source_token_indices",
]
